# Generated by Django 6.0.4 on 2026-07-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('bar', 'Бар'), ('pub', 'Паб'), ('restaurant', 'Ресторан'), ('cafe', 'Кафе'), ('coffee', "Кав'ярня"), ('club', 'Нічний клуб'), ('other', 'Інше')], default='other', max_length=20),
        ),
    ]
