# Generated by Django 6.0.4 on 2026-05-05 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_time', models.TimeField()),
                ('goal_description', models.TextField()),
                ('contact_me', models.CharField(max_length=255)),
                ('gender_preferences', models.CharField(max_length=255)),
                ('people_count', models.PositiveSmallIntegerField()),
                ('payer_type', models.CharField(choices=[('me', 'Me'), ('split', 'Split'), ('other', 'Other')], default='me', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangouts', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangouts', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Hangout Request',
                'verbose_name_plural': 'Hangout Requests',
                'db_table': 'hangout_requests',
            },
        ),
    ]
